AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS CloudFormation template for deploying an EC2 instance in a particular zone"

Resources:
 Ec2Instance:
   Type: AWS::EC2::Instance
   Properties:
     AvailabilityZone: us-east-1a
     ImageId: ami-0fc5d935ebf8bc3bc
